### ISSUE TITLE
How to ForceDischarge on demand?

### ISSUE THREAD

**Issue by ikassi** [TonyM1958/FoxESS-Cloud#20]
I am looking for a way to issue a forceDischarge from the API but so far I couldn't find any way of doing it even with the scheduler enabled. Is it possible at all through this library?

**Comment by TonyM1958** [comment]
It aims to provide a consistent interface for both although there are undelying differences in the way Fox has implemented them. It depends on which module you import and initialise. The main difference is which variables you set for your authentication. You cannot use both at the same time.

Largely equivalent API and application code entry points are available in both modules.

**Comment by ikassi** [comment]
Thank you!
