### ISSUE TITLE
illegal timestamp

### ISSUE THREAD

**Issue by ondrej337** [TonyM1958/FoxESS-Cloud#6]
Hi,
** get_access(), no result data, errno = 40256: Parameter could not be parsed correctly illegal timestamp

Can you check it please?

**Comment by ondrej337** [comment]
function: def signed_header(path, login = 0):
    **t_now = time.time()**
    **timestamp = str(round(t_now * 1000))**

**Comment by ondrej337** [comment]
Seems foxesscloud company  issue
https://www.foxesscloud.com/public/i18n/en/OpenApiDocument.html#3
your timestamp is correct: 
timestamp | Yes |   | Current timestamp milliseconds

**Comment by ondrej337** [comment]
I am UTC+1
Parameter: f.time_zone = "Europe/Prague"
result of the function: ** get_access(), no result data, errno = 40256: Parameter could not be parsed correctly illegal timestamp

I run only:
import foxesscloud.openapi as f

# add your info here
f.api_key = "xxx"
f.device_sn = "xxx"
f.time_zone = "Europe/Prague"

f.get_access_count()

**Comment by TonyM1958** [comment]
Ok, can you try increasing the debug level and running again. like this so we can see what the header being sent looks like. This is what it looks like for me:

![image](https://github.com/TonyM1958/FoxESS-Cloud/assets/63789168/aa2e61ea-99c3-4b8d-bbd9-0d0c4dfda8b5)

**Comment by TonyM1958** [comment]
another thing to check is that your system time and time zone are set correctly as time.time() returns a UTC times that relies on the system clock for it's offset.

**Comment by ondrej337** [comment]
thank you so much, my time was not correct, so I installed ntp service which synchronize time correctly. You can close the issue.

**Comment by TonyM1958** [comment]
OK - glad it's working for you now.
