### ISSUE TITLE
Not an issue! :) 

### ISSUE THREAD

**Issue by ramotswa** [TonyM1958/FoxESS-Cloud#8]
Tony - great repo here. Having just gotten setup with panels + battery and on octopus etc I was thinking to myself - I need to look if the Fox ESS has an API to do stuff programatically! And here someone has already done everything.

Out of interest, how do you run this logistically? Do you execute your daily notebook once a day yourself or have you set it up on something like a lambda to run once a day (probs what I'll do). 

I'm going to give this a spin for a few days and see how it all goes - just need to move to a better tariff first. 

What I'm probably going to have to do is extend it to encompass my EV charging - that should be fun.

**Comment by TonyM1958** [comment]
My setup and how to replicate stuff is described in the Wiki.

I use Anaconda for local interactive development but as I have Home Assistant, I tend to use Studio Code Server and Jupyter Lab Lite for most of the development and testing.

Scheduled jobs run scripts in Saturn Cloud that setup my battery charging each day and upload generation data to pvoutput. I used a paid for account. Running a daily job for a new minutes costs around $10 a year.

I don't have an EV but a lot of people recommend using MyEnergi Zappi. There isn't an official API so far as I understand, but some stuff is out there, for example, https://github.com/ashleypittman/mec?tab=readme-ov-file and https://github.com/twonk/MyEnergi-App-Api
